var tree = [["Icecave",,"",
                [["Coro","Icecave\/Coro.html","",
                [["Channel","Icecave\/Coro\/Channel.html","",
                [["Exception","Icecave\/Coro\/Channel\/Exception.html","",
                [["ChannelClosedException","Icecave\/Coro\/Channel\/Exception\/ChannelClosedException.html"," < Exception",
                [        ]],["ChannelExceptionInterface","Icecave\/Coro\/Channel\/Exception\/ChannelExceptionInterface.html","",
                [        ]]        ]],["Channel","Icecave\/Coro\/Channel\/Channel.html","",
                [        ]],["ChannelInterface","Icecave\/Coro\/Channel\/ChannelInterface.html","",
                [        ]],["ReadableChannelInterface","Icecave\/Coro\/Channel\/ReadableChannelInterface.html","",
                [        ]],["WritableChannelInterface","Icecave\/Coro\/Channel\/WritableChannelInterface.html","",
                [        ]]        ]],["Coroutine","Icecave\/Coro\/Coroutine.html","",
                [["Coroutine","Icecave\/Coro\/Coroutine\/Coroutine.html"," < AbstractParentTask",
                [        ]],["CoroutineInterface","Icecave\/Coro\/Coroutine\/CoroutineInterface.html","",
                [        ]],["DriverInterface","Icecave\/Coro\/Coroutine\/DriverInterface.html","",
                [        ]],["GeneratorDriver","Icecave\/Coro\/Coroutine\/GeneratorDriver.html","",
                [        ]]        ]],["Engine","Icecave\/Coro\/Engine.html","",
                [["AbstractEngine","Icecave\/Coro\/Engine\/AbstractEngine.html","",
                [        ]],["EngineInterface","Icecave\/Coro\/Engine\/EngineInterface.html","",
                [        ]],["Facade","Icecave\/Coro\/Engine\/Facade.html","",
                [        ]],["FacadeInterface","Icecave\/Coro\/Engine\/FacadeInterface.html","",
                [        ]],["FacadeOperation","Icecave\/Coro\/Engine\/FacadeOperation.html","",
                [        ]],["SynchronousEngine","Icecave\/Coro\/Engine\/SynchronousEngine.html"," < AbstractEngine",
                [        ]],["TaskRoot","Icecave\/Coro\/Engine\/TaskRoot.html","",
                [        ]]        ]],["React","Icecave\/Coro\/React.html","",
                [["EventLoopEngine","Icecave\/Coro\/React\/EventLoopEngine.html"," < AbstractEngine",
                [        ]],["PromisePrimitive","Icecave\/Coro\/React\/PromisePrimitive.html"," < AbstractTask",
                [        ]],["ReactFacade","Icecave\/Coro\/React\/ReactFacade.html"," < Facade",
                [        ]],["ReactTaskAdaptor","Icecave\/Coro\/React\/ReactTaskAdaptor.html"," < TaskAdaptor",
                [        ]]        ]],["Task","Icecave\/Coro\/Task.html","",
                [["Compound","Icecave\/Coro\/Task\/Compound.html","",
                [["WaitAll","Icecave\/Coro\/Task\/Compound\/WaitAll.html"," < AbstractParentTask",
                [        ]],["WaitAllResult","Icecave\/Coro\/Task\/Compound\/WaitAllResult.html","",
                [        ]],["WaitAny","Icecave\/Coro\/Task\/Compound\/WaitAny.html"," < AbstractParentTask",
                [        ]],["WaitAnyResult","Icecave\/Coro\/Task\/Compound\/WaitAnyResult.html","",
                [        ]]        ]],["Exception","Icecave\/Coro\/Task\/Exception.html","",
                [["TaskAdaptationException","Icecave\/Coro\/Task\/Exception\/TaskAdaptationException.html"," < LogicException",
                [        ]],["TaskCancelledException","Icecave\/Coro\/Task\/Exception\/TaskCancelledException.html"," < RuntimeException",
                [        ]],["TaskExceptionInterface","Icecave\/Coro\/Task\/Exception\/TaskExceptionInterface.html","",
                [        ]],["TaskTimeoutException","Icecave\/Coro\/Task\/Exception\/TaskTimeoutException.html"," < RuntimeException",
                [        ]]        ]],["Primitives","Icecave\/Coro\/Task\/Primitives.html","",
                [["ImmediatePrimitive","Icecave\/Coro\/Task\/Primitives\/ImmediatePrimitive.html"," < AbstractTask",
                [        ]],["ReturnPrimitive","Icecave\/Coro\/Task\/Primitives\/ReturnPrimitive.html"," < AbstractTask",
                [        ]],["SleepPrimitive","Icecave\/Coro\/Task\/Primitives\/SleepPrimitive.html"," < AbstractTask",
                [        ]],["SuspendPrimitive","Icecave\/Coro\/Task\/Primitives\/SuspendPrimitive.html"," < AbstractTask",
                [        ]],["ThrowPrimitive","Icecave\/Coro\/Task\/Primitives\/ThrowPrimitive.html"," < AbstractTask",
                [        ]],["TimeoutPrimitive","Icecave\/Coro\/Task\/Primitives\/TimeoutPrimitive.html"," < AbstractParentTask",
                [        ]]        ]],["AbstractParentTask","Icecave\/Coro\/Task\/AbstractParentTask.html"," < AbstractTask",
                [        ]],["AbstractTask","Icecave\/Coro\/Task\/AbstractTask.html","",
                [        ]],["TaskAdaptor","Icecave\/Coro\/Task\/TaskAdaptor.html","",
                [        ]],["TaskAdaptorInterface","Icecave\/Coro\/Task\/TaskAdaptorInterface.html","",
                [        ]],["TaskInterface","Icecave\/Coro\/Task\/TaskInterface.html","",
                [        ]],["TaskParentInterface","Icecave\/Coro\/Task\/TaskParentInterface.html","",
                [        ]],["TaskProviderInterface","Icecave\/Coro\/Task\/TaskProviderInterface.html","",
                [        ]],["TaskStatus","Icecave\/Coro\/Task\/TaskStatus.html"," < Enumeration",
                [        ]]        ]],["Coro","Icecave\/Coro\/Coro.html","",
                [        ]],["PackageInfo","Icecave\/Coro\/PackageInfo.html","",
                [        ]]        ]]        ]]        ]

